paginator-swagger
OlehReex/online-book-store pull request #5
Opened 2023-10-24 10:21 UTC by OlehReex

2023-10-24 15:48 UTC, Alexsandr-Yablunovskyi approved these changes
Nice work)

2023-10-25 07:59 UTC, Elena-Bruyako requested changes
Good job! Let's make your code better!

2023-10-25 07:59 UTC, Elena-Bruyako commented on pom.xml
> +            <version>3.1.5</version>
spring-boot-starter-parent already provide this version

2023-10-25 07:59 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        body.put("status", HttpStatus.BAD_REQUEST);
It's redundant to add status here, as you will have it in response

2023-10-25 07:59 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/validation/IsbnValidator.java
> +    private static final String ISBN_PATTERN = "^\\d{2}-\\d{3}-\\d{3}-\\d{2}$";
```suggestion
    private static final Pattern ISBN_PATTERN = Pattern.compile("^\\d{2}-\\d{3}-\\d{3}-\\d{2}$");
```

2023-10-25 07:59 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controller/BookController.java
>      public BookDto getBookById(@PathVariable Long id) {
You can also validate @PathVariable by using @Positive and add @Validated annotation on your controller class (optional comment)

2023-10-25 15:51 UTC, Andriy-dz approved these changes

2023-10-25 17:54 UTC, merged