category implementation
OlehReex/online-book-store pull request #7
Opened 2023-11-01 18:58 UTC by OlehReex

2023-11-05 10:27 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasAnyRole('ROLE_USER', 'ROLE_ADMIN')")
1. you may omit `ROLE_` prefix - it is included within `hasRole` as is
2. shouldn't admin user also have a role `USER`? or you design your app in a way that admin does not have same priviliges as user has?

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/controller/CategoryController.java
> +    public List<CategoryDto> getAll(Pageable pageable) {
consider using `@PageableDefault` in case client did not provide pagination params

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/controller/CategoryController.java
> +    public CategoryDto createCategory(@RequestBody CategoryRequestDto requestDto) {
shouldn't you validate request body here?

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/controller/CategoryController.java
> +                                              @RequestBody CategoryRequestDto requestDto) {
shouldn't you validate request body here?

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/controller/CategoryController.java
> +
```suggestion
```

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/controller/CategoryController.java
> +    public void deleteCategory(@PathVariable Long id) {
shouldn't you validate id here?

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/mapper/BookMapper.java
> +    }
this method does nothing - pls add implementation

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/service/impl/CategoryServiceImpl.java
> +                        "Can't find category with id " + id)));
you can simplify it:
```
return repo.findById(id)
          .map(mapper::toDto)
          .orElseThrow(...);
```

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/service/impl/CategoryServiceImpl.java
> +        return categoryMapper.categoryToResponseDto(categoryToSave);
```suggestion
        return categoryMapper.categoryToResponseDto(categoryRepository.save(categoryToSave));
```

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/service/impl/CategoryServiceImpl.java
> +        categoryRepository.deleteById(id);
what if there's no category with such id?

2023-11-05 10:27 UTC, NazarSmith228 commented on src/main/resources/db/changelog/changes/03-create-users-table.yaml
> +                  type: varchar(60)
pls avoid updating existing migrations in future

while this is ok for local setup (you just clear Liquibase tables in your local DB), it is not ok for real environment

therefore don't get used to it

2023-11-07 16:17 UTC, liliia-ponomarenko requested changes
Can you create a book with categories? Let’s add categoryIds field to CreateBookRequestDto and modify create and update book methods;)

2023-11-07 16:17 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ADMIN')")
```
check other endpoints

2023-11-08 08:02 UTC, NazarSmith228 approved these changes
LGTM, but please pay attention to my comment

2023-11-08 08:02 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/controller/BookController.java
> +    public List<BookDto> getAll(@PageableDefault(size = 10) Pageable pageable) {
you may also add `@ParameterObject` to describe this pageable on Swagger

2023-11-08 12:43 UTC, merged