Shopping cart
OlehReex/online-book-store pull request #8
Opened 2023-11-12 17:48 UTC by OlehReex

2023-11-13 14:32 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2023-11-13 14:32 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/model/CartItem.java
> +    @JoinColumn(name = "book_id", nullable = false)
pls add optional = false since cart item can't exist without book

2023-11-13 14:32 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
the same

2023-11-13 14:32 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/model/ShoppingCart.java
> +    @OneToOne(fetch = FetchType.LAZY)
the same

2023-11-13 14:32 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/model/ShoppingCart.java
> +    private Set<CartItem> cartItems;
```suggestion
    private Set<CartItem> cartItems  = new HashSet<>();
```

2023-11-13 14:32 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/repository/CartItemRepository.java
> +    CartItem findByShoppingCartIdAndBookId(Long cartId, Long bookId);
better return  Optional

2023-11-13 14:32 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/repository/ShoppingCartRepository.java
> +    @EntityGraph(attributePaths = {"cartItems", "user", "cartItems.book"})
do you need all related entities?

2023-11-13 14:32 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Override
Should you use Transactional with some methods?

2023-11-13 14:32 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/model/ShoppingCart.java
> +public class ShoppingCart {
Should you make a soft delete?

2023-11-13 14:32 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                new EntityNotFoundException("Can't find user with username: " + userName));
you can use  getPrincipal()

2023-11-15 10:15 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-11-15 10:15 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controller/ShoppingCartController.java
> +            @PathVariable @Positive Long cartItemId, @RequestBody CartItemQuantityDto quantityDto) {
```suggestion
            @PathVariable @Positive Long cartItemId, @RequestBody @Valid CartItemQuantityDto quantityDto) {
```

2023-11-15 10:15 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controller/ShoppingCartController.java
> +    public CartItemResponseDto addBookToCart(@RequestBody CartItemRequestDto cartItemRequestDto) {
```suggestion
    public CartItemResponseDto addBookToCart(@RequestBody @Valid CartItemRequestDto cartItemRequestDto) {
```

2023-11-15 10:15 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/model/ShoppingCart.java
> +public class ShoppingCart {
Not fixed

2023-11-15 10:15 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/repository/CartItemRepository.java
> +
remove empty line

2023-11-15 10:15 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Transactional
you can add readOnly = true as you don't want to change the data

2023-11-17 14:16 UTC, Elena-Bruyako approved these changes
Approve. But left one comment

2023-11-17 14:16 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/repository/CartItemRepository.java
> +public interface CartItemRepository extends JpaRepository<CartItem, Long> {
@Repository

2023-11-25 15:03 UTC, merged