Order implementation
OlehReex/online-book-store pull request #9
Opened 2023-11-15 21:46 UTC by OlehReex

2023-11-20 08:47 UTC, NazarSmith228 requested changes
I see this PR contains changes, irrelevant to Order task. This makes it hard to review. Pls split the PR, or choose other target branch (the one, where ShoppingCart is implemented)

2023-11-27 15:47 UTC, Elena-Bruyako requested changes
Good job!

2023-11-27 15:47 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controller/OrderController.java
> +    public CreateOrderResponseDto createOrder(@RequestBody CreateOrderRequestDto orderRequestDto) {
```suggestion
    public CreateOrderResponseDto createOrder(@RequestBody @Valid CreateOrderRequestDto orderRequestDto) {
```

2023-11-27 15:47 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controller/OrderController.java
> +                                               @RequestBody UpdateStatusRequestDto statusRequest) {
```suggestion
                                               @RequestBody @Valid UpdateStatusRequestDto statusRequest) {
```

2023-11-27 15:47 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/dto/order/OrderItemResponseDto.java
> +
remove empty line

2023-11-27 15:47 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/service/impl/OrderServiceImpl.java
> +        newOrder.setUser(shoppingCart.getUser());
It looks like this logic should be done by mapper

2023-11-27 15:47 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/service/impl/OrderServiceImpl.java
> +                shoppingCartRepository.findByUserId(getUser().getId()).orElseThrow(() ->
It's better to create variable for this. 
Bad practice to make logic instead of method argument

2023-12-01 13:04 UTC, liliia-ponomarenko approved these changes
Great! 😊

2023-12-01 16:01 UTC, merged